// import logo from './logo.svg';
// import './App.css';

// function App() {
//   return (
//     <div className="App">
//       <header className="App-header">
//         <img src={logo} className="App-logo" alt="logo" />
//         <p>
//           Edit <code>src/App.js</code> and save to reload.
//         </p>
//         <a
//           className="App-link"
//           href="https://reactjs.org"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Learn React
//         </a>
//       </header>
//     </div>
//   );
// }

// export default App;


import React, { useState, useEffect } from 'react';
import { 
  ShieldAlert, Bug, CheckCircle2, AlertTriangle, 
  LayoutDashboard, Search, Activity, ChevronRight, 
  ExternalLink, RefreshCw 
} from 'lucide-react';

const App = () => {
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Function to load the REAL data generated by Python
  const loadScanResults = async () => {
    setLoading(true);
    try {
      // Python Engine 'frontend/public/data/final_report.json' mein file save karta hai
      const response = await fetch('./data/final_report.json');
      if (!response.ok) throw new Error("Report file abhi tak bani nahi hai. Pehle Python Scanner chalayein.");
      
      const data = await response.json();
      setReportData(data);
      setError(null);
    } catch (err) {
      setError(err.message);
      // Fallback to empty structure if file missing
      setReportData({
        project_info: { target_app: "No Active Scan", scan_time: "N/A", total_bugs: 0 },
        summary: { critical: 0, warning: 0, info: 0 },
        findings: []
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadScanResults();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center text-emerald-500">
        <div className="animate-spin mb-4"><RefreshCw size={48} /></div>
        <p className="text-xl font-mono animate-pulse">Connecting to Python Engine...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans">
      {/* Sidebar */}
      <aside className="fixed left-0 top-0 h-full w-64 bg-slate-900 border-r border-slate-800 p-6 hidden lg:block">
        <div className="flex items-center gap-3 mb-10 text-emerald-400">
          <ShieldAlert size={32} />
          <h1 className="text-xl font-bold tracking-tight text-white uppercase">Bug Hunter</h1>
        </div>
        <nav className="space-y-2">
          <div className="flex items-center gap-3 p-3 bg-emerald-500/10 text-emerald-400 rounded-lg">
            <LayoutDashboard size={18} /> <span className="text-sm font-medium">Live Dashboard</span>
          </div>
          <div className="flex items-center gap-3 p-3 text-slate-500 hover:bg-slate-800 rounded-lg cursor-not-allowed">
            <Search size={18} /> <span className="text-sm">Deep Scan</span>
          </div>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="lg:ml-64 p-4 md:p-8">
        {error && (
          <div className="bg-red-500/10 border border-red-500/20 p-4 rounded-xl mb-6 text-red-400 text-sm flex items-center gap-3">
            <AlertTriangle size={18} /> {error}
          </div>
        )}

        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div>
            <h2 className="text-3xl font-bold text-white tracking-tight">System Audit</h2>
            <div className="flex items-center gap-2 mt-2 text-slate-400">
              <span className="text-sm">Target:</span>
              <span className="text-emerald-400 font-mono text-sm">{reportData?.project_info?.target_app}</span>
              <ExternalLink size={14} className="text-slate-600" />
            </div>
          </div>
          <button 
            onClick={loadScanResults}
            className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg transition-all border border-slate-700"
          >
            <RefreshCw size={16} /> Refresh Data
          </button>
        </header>

        {/* Status Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10 text-red-500"><ShieldAlert size={60} /></div>
            <p className="text-slate-500 text-xs font-bold uppercase tracking-wider">Critical Bugs</p>
            <h3 className="text-4xl font-black text-white mt-2">{reportData?.summary?.critical || 0}</h3>
          </div>
          <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10 text-orange-500"><AlertTriangle size={60} /></div>
            <p className="text-slate-500 text-xs font-bold uppercase tracking-wider">Warnings</p>
            <h3 className="text-4xl font-black text-white mt-2">{reportData?.summary?.warning || 0}</h3>
          </div>
          <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10 text-blue-500"><Activity size={60} /></div>
            <p className="text-slate-500 text-xs font-bold uppercase tracking-wider">Total Scanned</p>
            <h3 className="text-4xl font-black text-white mt-2">{reportData?.findings?.length || 0}</h3>
          </div>
        </div>

        {/* Table Area */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl">
          <div className="p-6 border-b border-slate-800 flex items-center justify-between">
            <h3 className="font-bold text-white uppercase text-sm tracking-widest">Vulnerability Log</h3>
            <span className="bg-emerald-500/20 text-emerald-400 px-2 py-1 rounded text-[10px] font-bold">LIVE ENGINE</span>
          </div>
          
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="text-slate-500 text-[11px] uppercase tracking-tighter border-b border-slate-800">
                  <th className="px-6 py-4 font-bold">Vulnerability</th>
                  <th className="px-6 py-4 font-bold">Severity</th>
                  <th className="px-6 py-4 font-bold">Path/Location</th>
                  <th className="px-6 py-4 font-bold text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {reportData?.findings?.length > 0 ? reportData.findings.map((bug, idx) => (
                  <tr key={idx} className="hover:bg-white/[0.02] transition-colors group">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <Bug size={16} className={bug.severity === 'Critical' ? 'text-red-500' : 'text-orange-400'} />
                        <span className="text-sm font-semibold text-slate-200">{bug.type}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${
                        bug.severity === 'Critical' ? 'bg-red-500/10 border-red-500/20 text-red-500' : 'bg-orange-500/10 border-orange-500/20 text-orange-500'
                      }`}>
                        {bug.severity}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-xs text-slate-500 font-mono">
                      {bug.description}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button className="text-slate-600 group-hover:text-emerald-400 transition-colors">
                        <ChevronRight size={18} />
                      </button>
                    </td>
                  </tr>
                )) : (
                  <tr>
                    <td colSpan="4" className="px-6 py-10 text-center text-slate-600 italic">
                      No bugs found yet. Start a scan to see results.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;